trigger:
- master


stages:
- stage: Build
  
  jobs:

  # #####################################################
  # Android
  # #####################################################
  - job: Android

    steps:
      - template: android/_restore.yml
      - template: android/_build.yml
        parameters:
          task: 'assembleRelease'
      #- template: android/_sign.yml
      - template: android/_publish.yml
    pool:
      vmImage: 'macos-latest'
