trigger: none # will disable CI builds entirely

stages:
- stage: Build
  
  jobs:

  # #####################################################
  # Android
  # #####################################################
  - job: Android
    variables:
    - group: GooglePlay_SigningCert_com.artezio.osport.tracker
    - group: GoogleMap_com.artezio.osport.tracker
 
    steps:
      - template: android/_restore.yml
      - template: android/_build.yml
        parameters:
          task: 'assembleRelease'
    pool:
      vmImage: 'macos-latest'