trigger: none # will disable CI builds entirely

stages:
- stage: Build
  
  jobs:

  # #####################################################
  # Android
  # #####################################################
  - job: Android
    variables:
    - name: mapkey  # name of a variable
      value: AIzaSyD7RxeX40rzTHV0pg5GBdZgJLj6dYWfBOw # value of the variable

    steps:
      - template: android/_restore.yml
      - template: android/_build.yml
        parameters:
          task: 'assembleRelease'
    pool:
      vmImage: 'macos-latest'