trigger: none # will disable CI builds entirely

stages:
- stage: Build
  
  jobs:

  # #####################################################
  # Android
  # #####################################################
  - job: Android

    steps:
      - template: android/_restore.yml
      - template: android/_build.yml
    pool:
      vmImage: 'macos-latest'