trigger:
- releases/*

stages:
- stage: Build
  
  jobs:

  # #####################################################
  # Android
  # #####################################################
  - job: Android
    variables:
    - group: GooglePlay_SigningCert_com.artezio.osport.tracker
    - group: GoogleMap_com.artezio.osport.tracker

    steps:
      - template: android/_restore.yml
      - template: android/_build.yml
        parameters:
          task: ':app:bundleRelease'
      - template: android/_sign.yml
        parameters:
          archiveType: 'aab'
      - template: android/_publish.yml
    pool:
      vmImage: 'macos-latest'